portfolio:
  tickers: ["ASML.AS","AD.AS","PHIA.AS","NN.AS","URW.AS","AAPL","MSFT","NVDA","ZSIL.SW","ZPLA.SW","DNN","FVL.TO","FNV","SBSW","MAG","DSV.V"]

  weights: null  # of vul handmatig in, bv: {"ASML.AS":0.1, ...}

watchlist: []

sectors:
  Tech: ["ASML.AS", "PHIA.AS", "AAPL", "MSFT", "NVDA"]
  Financials: ["NN.AS"]
  RealEstate: ["URW.AS"]
  Consumer: ["AD.AS"]
  Materials: ["FNV", "MAG", "SBSW", "DNN", "FVL.TO", "ZSIL.SW", "ZPLA.SW"]
  Logistics: ["DSV.TO"]

signals:
  ma_short: 20
  ma_long: 50
  rsi_period: 14
  rsi_buy: 35
  rsi_sell: 65

data:
  lookback_days: 365

reporting:
  currency: "EUR"

news:
  provider: "auto"   # auto | newsapi | finnhub
  per_ticker: 8

risk:
  target_vol: 0.15

system:
  regime_filter: true        # alleen long als prijs > SMA200
  macd_confirm:  true        # koop alleen als MACD > signaal (verkoop: MACD < signaal)
  hysteresis_days: 2         # cross moet x dagen standhouden
  stop_loss_pct: 0.08        # 8% onder entry
  take_profit_pct: 0.16      # 16% boven entry
  risk_per_trade_pct: 0.5    # % van portefeuille-waarde per trade (risicobudget)
  max_positions: 8
  use_atr: true              # sizing met ATR; anders simpele vol
  atr_window: 14
  capital_eur: 25000         # nodig voor sizing (pas aan)
